apiVersion: v1
kind: Service
metadata:
  name: blood-classifier
spec:
  type: NodePort
  selector:
    app: blood-classifier
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080